name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image basic tern
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: docker/Dockerfile
          tags: ronkabu0401/tern:latest
          labels: ronkabu0401.tern.docker.source=https://github.com/ron0401/tern.git
      
      - name: Build and push Docker image tern with scancode
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: docker/Dockerfile.scancode
          tags: ronkabu0401/tern:scancode
          labels: ronkabu0401.tern.scancode.docker.source=https://github.com/ron0401/tern.git
